"""initial migration

Revision ID: 40f3fc9f6606
Revises: 
Create Date: 2025-04-03 22:50:36.801452

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40f3fc9f6606'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=20), nullable=True))
        batch_op.drop_column('contact_number')
        batch_op.drop_column('car_plate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('car_plate', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('contact_number', sa.VARCHAR(length=20), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
